language: ruby
services: mongodb
bundler_args: --without development
rvm:
- 1.9.3
- 2.0.0
deploy:
  provider: rubygems
  api_key:
    secure: hWkNBQ4LbxAsErQZ8X46SKvCQ2tRwMU/SX2cWPlE0izXPvlpRie7HQvqlcCdmaYhxljxVEOdThMS9UW8rm4e+ykuWic0SD04iod7c9uvQQIxLra49lawOwaRkARRJJXcU5vIs+DXPEODsnRUita2llCf6WNyKbU+4mPacrC+AH4=
  gem: mongoid_listable
  on:
    tags: true
    repo: richardcalahan/mongoid_listable
